# IceBoatRacing, a powerful plugin for your ice boat racing server.
# - Developed by mattmunich
#
# ----------------------------------------------------------------
# Welcome to the main configuration file of this plugin.
# Below, you can change the main settings for this plugin,
# like the language, the number of laps required to finish
# a race and more.
# ----------------------------------------------------------------
# Some instructions:
# - The default value for race.lights.x/y/z is 123456789,
#   if they are read by the plugin, the race lights are
#   automatically disabled.
# ----------------------------------------------------------------

# Will read from the file [language].yml, so by default: en_US.yml
language: en_US

# Configure the race.
race:
  # Whether a player should be allowed to continue racing even after logging out and back in
  allowRejoin: true

  # The racer's GameMode during the race
  ## Use ADVENTURE, SURVIVAL or CREATIVE (will probably not work with SPECTATOR)
  racingGameMode: ADVENTURE

  # Will prevent the checkpoints for working if the racer's
  # GameMode is not `racingGameMode`
  enforceRacingGameMode: true

  # Whether the player should be put is spectator mode when they finish the race.
  ## - true: player will be put in spectator mode
  ## - false: player will remain on track and be able to freely continue boating
  spectateOnFinish: true

  # Whether a player's car should be removed when they log out
  ## If allowRejoin is false, the car will always be removed
  removeCarWhenLoggingOut: false

  # Configure the race lights
  # -> colored glass that will change on
  #    race start to simulate race lights
  lights:
    enabled: false
    from:
      x: 123456789
      y: 123456789
      z: 123456789
    to:
      x: 123456789
      y: 123456789
      z: 123456789